#!/bin/bash

# internsctl script to get CPU and Memory information

case $1 in
    "cpu")
        case $2 in
            "getinfo")
                cpu_info=$(lscpu)
                echo "CPU Information:"
                echo "$cpu_info"
                ;;
            *)
                echo "Invalid argument for 'cpu'. Use 'getinfo'."
                exit 1
                ;;
        esac
        ;;
    "memory")
        case $2 in
            "getinfo")
                mem_info=$(free)
                echo "Memory Information:"
                echo "$mem_info"
                ;;
            *)
                echo "Invalid argument for 'memory'. Use 'getinfo'."
                exit 1
                ;;
        esac
        ;;
    *)
        echo "Usage: $0 {cpu|memory} getinfo"
        exit 1
        ;;
esac

